dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  # Install conda
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -n base -c defaults conda
  - conda create -n ccc-dev python=$TRAVIS_PYTHON_VERSION;
  - source activate ccc-dev
  - conda env update -f environment.yml
  - pip install codecov
  - pip install .

# command to run tests
script:
  - python -c "import ccc"; coverage run -m pytest -v -m 'not needs_puf' --pep8

after_success:
  - codecov
