name: ccc-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python
- "taxcalc>=3.0.0"
- "paramtools>=0.14.2"
- "bokeh>=1.4.0"
- setuptools
- pip
- xlrd
- openpyxl
- pytest
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- pip:
  - cs-kit
