name: ccc-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python
- "taxcalc>=2.4.0"
- "paramtools>=0.7.1"
- setuptools
- pip
- xlrd
- pytest
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
