name: ccc-dev
channels:
- PSLmodels
- conda-forge
dependencies:
- python=3.6
- taxcalc
- setuptools
- pytest
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- "paramtools>=0.5.1"
- pip
- pip:
  - git+https://github.com/comp-org/Developer-Tools.git@master
