package:
  name: ccc
  version: 1.0.0

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - taxcalc
    - setuptools
    - paramtools >=0.5.1

about:
  home: https://github.com/open-source-economics/Cost-of-Capital-Calculator/


test:
  imports:
    - ccc
    - ccc.data
    - ccc.parameters
    - ccc.calculator
    - ccc.calcfunctions
    - ccc.get_taxcalc_rates
    - ccc.styles
    - ccc.controls_callback_script
    - ccc.constants
    - ccc.utils
