package:
  name: ccc
  version: 0.0.0

source:
  path: ..

requirements:
  build:
    - python
    - "taxcalc>=2.4.2"
    - "bokeh>=1.2.0"
    - "paramtools>=0.7.1"
    - setuptools
    - xlrd

  run:
    - python
    - "taxcalc>=2.4.0"
    - setuptools
    - "paramtools>=0.7.1"
    - xlrd

about:
  home: https://github.com/open-source-economics/Cost-of-Capital-Calculator/

test:
  imports:
    - ccc
    - ccc.data
    - ccc.parameters
    - ccc.calculator
    - ccc.calcfunctions
    - ccc.get_taxcalc_rates
    - ccc.styles
    - ccc.controls_callback_script
    - ccc.constants
    - ccc.utils
